context:
  version: 9.1.5

package:
  name: husky
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/husky/-/husky-${{ version }}.tgz
  sha256: b8554e96b4ca517f648b8b3f4d7af5ac316a6fc72f3bfa2bcd4c39cc9b0e9e74

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
  run:
    - nodejs

tests:
  - script:
      - husky --help

about:
  license: MIT
  license_file: LICENSE
  summary: Git hooks made easy
  homepage: https://github.com/typicode/husky
  repository: https://github.com/typicode/husky

extra:
  recipe-maintainers:
    - danielnachun
